src/components/BookDetail.vue, src/components/BooksList.vue, src/model/Book.ts, src/model/IBook.ts
=> refs #4 本の一覧で不要な要素を生成しないようにする

src/model/Book.ts, src/model/IBook.ts
=> refs #8 Add model for rental usecase

src/model/Books.ts
=> refs #7 一覧情報の取得時に本のインスタンスが Book 型で生成されるようにする

src/components/BookDetail.vue, src/model/Book.ts, src/model/IBook.ts, src/model/Timestamp.ts
=> refs #12 貸出機能の追加

src/components/BookDetail.vue, src/model/Book.ts, src/model/IBook.ts
=> refs #15 返却機能の追加

package-lock.json, package.json, src/components/BookDetail.vue, src/components/BooksList.vue, src/main.ts, src/model/Book.ts, src/model/Books.ts, src/model/IBook.ts, src/model/User.ts
- 本来は $attrs を使って any 型以外の方法で解決したい
- 画面のリロードを行なっていないので、更新日が正しく変更されない
- Author が EditMode でなくても入力できてしまう
/closes #10
=> refs #10 本の編集機能を追加する

package-lock.json, package.json, src/components/BooksList.vue, src/plugins/vuetify.ts
=> refs #20 本リストの遅延ロードを可能にする

src/components/BookDetail.vue, src/model/Books.ts
=> refs #26 書籍リスト取得時にユーザ名の補完をawaitで待機しないようにする

src/components/BookDetail.vue, src/model/IUser.ts, src/modules/SignInModule.ts, src/views/BooksList.vue
=> refs #30 貸出中の書籍の詳細が正常に表示されない

package-lock.json, package.json, src/App.vue, src/components/BookDetail.vue, src/main.ts, src/plugins/vuetify.ts, src/views/Register.vue, src/views/SignIn.vue
=> refs #23 Vuetify Version up 1.5.5 to 2.0.4

src/components/BookDetail.vue, src/model/Books.ts, src/modules/BooksModule.ts
=> refs #21 データ更新時のリロードを有効にする

package-lock.json, package.json, src/plugins/vuetify.ts, src/shims-vue.d.ts
=> refs #23 Vuetify 2.0.7 へのバージョンアップ変更追従

src/views/BooksList.vue
=> refs #37 画像をクリッカブルにする

src/plugins/vuetify.ts, src/shims-vue.d.ts
=> refs #23 Vuetify の重複宣言を修正して build できるようにする

src/App.vue, src/components/BookDetail.vue, src/views/BookEventList.vue, src/views/BooksList.vue, src/views/Register.vue
=> refs #23 v-layout, v-flex を v-row, v-col に置換

src/modules/SignInModule.ts, src/router.ts
=> refs #59 Fix firebase import

functions/package-lock.json, functions/package.json, functions/src/index.ts, functions/src/onCreateBook.ts
=> refs #49 新しい本が追加されたら Slack に通知する

src/components/BookDetail.vue, src/model/Book.ts, src/views/BookEventList.vue, src/views/Register.vue
=> refs #56 ユーザ情報の取得方法を共通化

common/IBook.ts, common/IGoogleBookInfo.ts, functions/src/onCreateBook.ts, src/model/Book.ts, src/model/Books.ts, src/views/BooksList.vue, src/views/Register.vue
* Google books API のレスポンスを Interface として定義
* サムネイル画像だけでなく、解像度の高い画像も保持できるように
* リファクタ
* 推論可能な箇所は型定義を削除
* TODO コメントを追加
* 初期化パラメータを設定してトースト表示処理を簡略化
* 不要なアクセス修飾子を削除
=> refs #54 本の表示画像取得先 URL を HTTPS に変更

.env.develop, .vscode/launch.json
=> VS Code 拡張機能用のデバッグ設定を追加

.storybook/addons.ts, .storybook/config.ts, package-lock.json, package.json, src/components/BookDetail.stories.ts
初期状態を `iphonex` にしてみた。
[プリセット端末](https://github.com/storybookjs/storybook/blob/next/addons/viewport/src/defaults.ts)リストを画面から選択できるようになった。
=> refs #81 プリセットの ViewPort を利用可能にする

common/IBook.ts, src/components/BookDetail.vue, src/main.ts, src/model/Book.spec.ts, src/model/Book.ts, src/model/Books.ts, src/modules/BooksModule.ts, src/utilities/filters.ts, src/views/BooksList.vue, src/views/Register.vue
=> refs #84 Book class をやめて function にする

src/views/BooksList.vue
=> refs #88 Adjust layout of book list

src/App.vue
closes #94 
- ログアウト時はオーバーレイ表示して以降の操作を受け付けないようにする
=> refs #94 ログアウト メニューダイアログを表示する

.gitignore, package.json, src/main.ts, yarn.lock
closes #92 
- VUE_APP_ANALYTICS_ID を .env に指定
=> refs #92 Google Analytics の設定を追加

src/App.vue, src/components/BookDetail.vue, src/main.ts, src/plugins/vuetify.ts, src/router.ts, src/shims-vue.d.ts, src/views/BookEventList.vue, src/views/BooksList.vue, src/views/Register.vue
=> refs #104 Async component

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/nightly.yml, README.md, jest.config.js, package.json, yarn.lock
- Add secret `CODECOV_TOKEN`
- Add badge in README [![codecov](https://codecov.io/gh/es-dev-camp/books-management-service/branch/master/graph/badge.svg)](https://codecov.io/gh/es-dev-camp/books-management-service)
closes #110
=> refs #110 Install codecov

.storybook/main.ts, package.json, src/components/BookDetail.stories.ts, src/components/BookDetail.vue, yarn.lock
Storybook 上でダイナミックに内容を変更できるアドオンを追加  
https://storybook.js.org/docs/react/essentials/controls
=> refs #115 ✅ Add Storybook addon-essentials

public/index.html
This reverts commit f3df4b8b079e086a35dcb80c51aee39ae4dd667d.
アイコンが表示されなくなったため戻し
=> Revert "refs #109 🔥 Remove unused css references"

.eslintrc.js, package.json, yarn.lock
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
=> refs #147 Update eslint-config-prettier to 8.2.0
